# Generated by Django 3.1.7 on 2021-03-23 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEatingGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal', models.PositiveIntegerField(default=0, help_text='Дневной калораж')),
                ('carbs', models.PositiveIntegerField(default=0, help_text='Углеводы')),
                ('proteins', models.PositiveIntegerField(default=0, help_text='Белки')),
                ('fats', models.PositiveIntegerField(default=0, help_text='Жиры')),
                ('user', models.OneToOneField(help_text='Чья цель', on_delete=django.db.models.deletion.CASCADE, related_name='daly_eating_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
