# Generated by Django 3.1.7 on 2021-03-23 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название упражнения', max_length=128, unique=True)),
                ('muscle_type', models.CharField(choices=[('Спина', 'Спина'), ('Бицепс', 'Бицепс'), ('Трицепс', 'Трицепс'), ('Предплечье', 'Предплечье'), ('Грудь', 'Грудь'), ('Пресс', 'Пресс'), ('Ноги', 'Ноги'), ('Кардио', 'Кардио')], help_text='Тип упражнения', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Дата тренировки')),
                ('user', models.ForeignKey(help_text='Кто занимался', on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.PositiveIntegerField(help_text='Номер подхода в тренировке')),
                ('reps', models.PositiveIntegerField(help_text='Повторения')),
                ('exercise', models.ForeignKey(help_text='Упражнение', on_delete=django.db.models.deletion.CASCADE, related_name='gym_sets', to='Trainings.exercise')),
                ('training', models.ForeignKey(help_text='Тренировка', on_delete=django.db.models.deletion.CASCADE, to='Trainings.training')),
            ],
        ),
    ]
